### ISSUE TITLE
FakeModuleObject - SyntaxError

### ISSUE THREAD

**Issue by Krejdom** [zopefoundation/martian#3]
Hi,
I am getting the SyntaxError during the build of python-martian. Could you please tell me what is wrong?
```python
Compiling /home/user/rpmbuild/BUILDROOT/python-martian-0.15-1.fc24.x86_64/usr/lib/python2.7/site-packages/martian/testing_compat3.py ...
  File "/usr/lib/python2.7/site-packages/martian/testing_compat3.py", line 26
    class FakeModuleObject(object, metaclass=FakeModuleObjectMetaclass):
                                            ^
SyntaxError: invalid syntax
```

**Comment by mgedmin** [comment]
This is a test module only used on Python 3.  It is okay to ignore this error when you install martian for Python 2.

**Comment by Krejdom** [comment]
@mgedmin Thank you! :)

**Comment by mgedmin** [comment]
It would be very nice to figure out if we can find a way to _avoid_ that error, to avoid user confusion.

I've no idea how to do that. :-(

**Comment by Krejdom** [comment]
Could you run tests only when the Python 3 is used? Somehow like this: http://stackoverflow.com/questions/11277721/python-2-code-if-python-3-then-sys-exit but vice versa?

**Comment by mgedmin** [comment]
The errors reported here look like they're produced by Python's [compileall](https://docs.python.org/2/library/compileall.html) being run on all the .py files at install time, rather than while running tests.
